version: '3.9'

services:
    database:
        image: postgres:16-alpine
        container_name: db4${COMPOSE_PROJECT_NAME}
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "$POSTGRES_USER" ]
            interval: 40s
            timeout: 10s
            retries: 10
        volumes:
            #          - ./initdb:/docker-entrypoint-initdb.d/
            - postgres_data_dev:/var/lib/postgresql/data/
        ports:
            - "5432:5432"
        restart: always
volumes:
    postgres_data_dev:
