version: '3.9'

services:
    docid-backend:
        container_name: docid-backend
        build:
            context: ./
            dockerfile: Dockerfile-prod
        environment:
            - FLASK_APP=docid_app/__init__.py
            - FLASK_DEBUG=0
            - APP_SETTINGS=docid_app.config.ProductionConfig
            - DATABASE_URL=${DATABASE_URL}
        volumes:
            - ./:/usr/src/app
        expose:
            - "5000"
        depends_on:
            - docid-db
        links:
            - docid-db
        restart: always

    docid-db:
        container_name: docid-db
        build:
            context: ./db
            dockerfile: Dockerfile
        ports:
            - "5498:5432"
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        restart: on-failure

    docid-nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        container_name: docid-nginx
        ports:
            - "80:80"
        depends_on:
            - docid-backend
        restart: always
