version: '3.9'

services:
    docid-backend:
        container_name: docid-backend
        build:
            context: ./
            dockerfile: Dockerfile-dev
        environment:
            - FLASK_APP=docid_app/__init__.py
            - FLASK_DEBUG=1
            - APP_SETTINGS=docid_app.config.DevelopmentConfig
            - DATABASE_URL=postgresql://postgres:postgres@docid-db:5432/users_dev
            - DATABASE_TEST_URL=postgresql://postgres:postgres@docid-db:5432/users_test
        volumes:
            - ./:/usr/src/app
        ports:
            - "5099:5000"
        depends_on:
            - docid-db
        links:
            - docid-db
        restart: always

    docid-db:
        container_name: docid-db
        build:
            context: ./db
            dockerfile: Dockerfile
        ports:
            - "5498:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        restart: on-failure
