FROM python:3.10.12-bullseye

# Set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Add requirements
COPY ./requirements.txt /usr/src/app/requirements.txt

# Install requirements
RUN pip install -r requirements.txt

# Add app
COPY . /usr/src/app
# Run server
CMD python manage.py run -h 0.0.0.0
