FROM python:3.10.12-bullseye

# Set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install pipenv
RUN pip install pipenv

# Add requirements
COPY Pipfile Pipfile.lock /usr/src/app/

# Install dependencies
RUN pipenv install --dev --system

# Add app
COPY . /usr/src/app

# Run server
CMD python manage.py run -h 0.0.0.0
